use strict;
use warnings;
use Bio::Seq;
use Bio::Tools::SeqStats;

# URL to check stats against.
#my $url = "http://www.bioinformatics.org/sms2/dna_stats.html";
my $dna = "GGAGCATAGCTACATGCCTAGTCTCAAATTATGCACATGAATGCCTATTCGATACGCACACGAATGCTGTTGACTTAGCAGCGCTACGCCCGGTAGGATTTCTCTAGTGCTAGCTATGGCCGCGATGGGAGAGCTATAGGATTAAACTGCATTCCGTGGATTAGTGGGGACTTCAGCATACGTAATGCATGTAAGACACCACTCGAACGTGTGCCAACGTTGGGGCTACTCGGGTTGAGCGCGAAAGACCCAATAGATCAGAGTAGACCCATCCACCCTTCTTGCATATCGATGCTGCACTGCGGGTCGACAAAGCTATCTGTTGCGTAGGATTAGTCATCCCCTACCGGCGATGCGTGATGTGGGCGTGCTAATTCCAGGTGATCGGGGTATCATAGGGATGCATCCGAAAAGATCGACTATCTTATAGGACTATTCCGTCTTTACTAAAATGAGATGTGCCCAGCTGTGGCGTTTCAGTAAGATGTCATCAGTGTGCATAACTAGATACATCAGTTTGACTACAATGCTCCAGATCTTTCAGCTGTCTCGCTTAATGCTGACACTGTCGGGAATCATTTTTACGCTGTACGGGTACTCCAAGGGTCAACCTATTAGAGGTTATAATATAGCTTCAGCCACTGTCAGTTGACCGGATACTCGGGGCCTGCTCGGCTTCTGTGAGTTTCGCGGATGTCTTATATCTCACTCCCATGGCCTTACATGCATAATACGCACCCACTATCAATAACCTGAGTATTAGACGCAGCCACACAGCTGTGAGAGATCGAAGGATACCTTCGTGGTGCGTCGCGGTGGTACAACCGACGTTCCTTTACGCATGT";
my $seq = Bio::Seq->new(-seq => $dna,
                        -alphabet => 'dna' );
print $seq->seq() . "\n";

my $stats = Bio::Tools::SeqStats->new(-seq => $seq);
my $counts = $stats->count_monomers();
print $counts->{"A"} . " " . $counts->{"C"} . " " .$counts->{"G"} . " " .$counts->{"T"} . " " . "\n";